export enum ForgotPasswordStep {
  PHONE_SPECIFICATION = 'PHONE_SPECIFICATION',
  VERIFICATION_CODE_SPECIFICATION = 'VERIFICATION_CODE_SPECIFICATION',
  PASSWORD_SPECIFICATION = 'PASSWORD_SPECIFICATION'
}
