name: Pull Request Check

env:
  IMAGE_NAME: "farm-trade-frontend-additional"
  IMAGE_REGISTRY: "ghcr.io"

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run NPM CI
        run: npm ci

# TODO Add test check
#      - name: Run NPM TEST
#        run: npm test

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ github.sha }}
          registry: ${{ env.IMAGE_REGISTRY }}
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Image Report
        run: echo Image name is ${{ env.IMAGE_REGISTRY }}/farm-trade/${{ env.IMAGE_NAME }}:${{ github.sha }}
